name: Create python source package
on: push

jobs:
  make-wavedrom:
    name: Compile wavedrom
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@2.0.0
      - name: Make
        run: make wavedrom
  sdist:
    name: Create package
    runs-on: ubuntu-latest
